version: "3.9"

services:
  nginx:
    image: nginx:1.21.4-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    image: nginx:1.21.4-alpine
    container_name: web
    expose:
      - 80
    volumes:
      - ./web/pages:/var/www/html/web
      - ./web/default.conf:/etc/nginx/conf.d/default.conf